// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:280473e1-ba89-44bb-b8ad-42c2f19e7904",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VKPqFnURu",
    "aws_user_pools_web_client_id": "6b6rff4qhsbgrc2fjrpm99epnc",
    "oauth": {},
    "aws_user_files_s3_bucket": "zatiqappstorage-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "zatiq-app-hosting-bucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1tqbyzvdf4s55.cloudfront.net"
};


export default awsmobile;
